---
- name: Clone repos, copy Dockerfiles, build images
  hosts: webserver
  become: yes
  vars_files:
    - vars/projects.yml

  tasks:
    - name: Install required packages
      include_tasks: tasks/install-packages.yml

    - name: Checking ssh connection
      include_tasks: tasks/ssh-agent.yml
    
    - block:
        - name: Clone all Git repositories
          include_tasks: tasks/services-repos.yml
      become: false
      become_user: rajesh

    - block:
        - name: Copying env to respective folders
          include_tasks: tasks/frontend-repos.yml
      become: true
      become_user: rajesh

    - name: Configuring the nginx url's
      include_tasks: tasks/nginx-conf.yml
    
    - block:
        - name: Creating docker containers
          include_tasks: tasks/docker-one.yml
      become: false
      become_user: rajesh

  handlers:
    - name: Restart Nginx
      become: yes
      ansible.builtin.service:
        name: nginx
        state: restarted