---
- name: Copy and render environment template for each repo
  template:
    src: "{{ item.src }}"     # Jinja2 template path
    dest: "{{ item.dest }}"   # Destination on server
    mode: "0644"
  loop: "{{ envs }}"
