---
- name: Remove old Docker versions if present
  become: yes
  apt:
    name:
      - docker
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install OpenJDK 17
  become: yes
  apt:
    name: openjdk-17-jdk
    state: present

- name: Set Java 17 as default
  become: yes
  shell: |
    update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 171
    update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 171
    update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

- name: Verify Java version
  command: java -version

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install required base packages
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
      - maven
      - python3-pip
      - nginx
    state: present

- name: Add Docker’s official GPG key
  become: yes
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  become: yes
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo $VERSION_CODENAME) stable" \
    > /etc/apt/sources.list.d/docker.list

- name: Update apt cache after adding Docker repo
  become: yes
  apt:
    update_cache: yes

- name: Install Docker Engine
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure nginx service is running
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Install Python Docker SDK
  become: yes
  shell: |
    python3 -m pip install docker --break-system-packages


- name: Add current user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
