- name: Remove old Docker versions if present
  apt:
    name:
      - docker
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

# -----------------------------------
# UPDATE PACKAGE CACHE
# -----------------------------------
- name: Update apt cache
  apt:
    update_cache: yes

# -----------------------------------
# INSTALL JAVA 17
# -----------------------------------
- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Set Java 17 as default using update-java-alternatives
  shell: |
    update-java-alternatives -s $(update-java-alternatives -l | grep 'java-1.17' | awk '{print $1}')
  register: set_java
  changed_when: "'no alternatives' not in set_java.stderr"

- name: Verify Java version
  command: java -version

# -----------------------------------
# INSTALL BASE UTILITIES
# -----------------------------------
- name: Install required base packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
      - maven
      - python3-pip
      - nginx
      - certbot
      - python3-certbot-nginx
      - python3-psycopg2
      - postgresql-{{ postgres_version }}
      - postgresql-client-{{ postgres_version }}
    state: present

# -----------------------------------
# INSTALL DOCKER
# -----------------------------------
- name: Add Docker’s official GPG key
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

# -----------------------------------
# ENSURE NGINX IS RUNNING
# -----------------------------------
- name: Ensure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

# -----------------------------------
# PYTHON DOCKER SDK & PERMISSIONS
# -----------------------------------
- name: Install Python Docker SDK
  shell: |
    python3 -m pip install docker --break-system-packages

- name: Add current user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Verify Docker is working (using sudo)
  shell: docker ps