version: '3.3'

services:
  test.kwc-redis:
    image: redis:7.2.4-alpine
    container_name: test.dadus-redis
    ports:
      - "6378:6378"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--port", "6378"]   
    networks:
      - test.kwc

  test.kwc-core-services:
    image: core-services:latest
    container_name: test.kwc-core-services
    ports:
      - "8787:8787"
    depends_on:
      - test.kwc-redis
    volumes:
      - ./core_application.properties:/core-services/application.properties
      - /home/ubuntu/Instances/KWC/Repos/cw-print-templates:/core-services/source/src/main/java/com/cw/erp/modules/cw-print-templates
      - ./core-service-logs:/core-services/cwbackoffice
      - /home/ubuntu/Instances/KWC/Compose/Release_management:/core-services/Release_management/
      - /home/ubuntu/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/ubuntu/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    command: ["java", "-jar", "/core-services/core-services.jar"]
    networks:
      - test.kwc
 
  test.kwc-retail-services:
    image: retail-services:latest
    container_name: test.kwc-retail-services
    ports:
      - "8888:8888"
    depends_on:
      - test.kwc-redis
    volumes:
      - ./retail_application.properties:/retail-services/application.properties
      - ./retail-logs:/retail-services/cwretail
    command: ["java", "-jar", "/retail-services/retail-service.jar"]
    networks:
      - test.kwc



volumes:
  redis-data:
    driver: local

networks:
  test.kwc:
    driver: bridge
